version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - mistic100
  labels:
  - dependabot
  ignore:
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
  - dependency-name: rollup-plugin-postcss
    versions:
    - 4.0.0
  - dependency-name: three
    versions:
    - 0.125.1
  - dependency-name: postcss-banner
    versions:
    - 4.0.0
