daysUntilStale: 7
daysUntilClose: 7
onlyLabels:
  - invalid
staleLabel: wontfix
markComment: >
  This issue has been automatically marked as wontfix because not enough
  information was provided. It will be closed if no further activity occurs.
closeComment: false
